_wandb:
    value:
        cli_version: 0.23.1
        e:
            3rf1t73a69ophjp0sbi5t9pyg0izjjxk:
                codePath: classification/classification_models/vit.py
                codePathLocal: vit.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "250685575168"
                        used: "232170741760"
                email: jeremyunderscore@gmail.com
                executable: /opt/anaconda3/envs/research_agent_env/bin/python
                git:
                    commit: 093423feddbf2412ea25730d64539c0fb9c5f5ad
                    remote: git@github.com:JeremyOng96/research_agent.git
                host: MacBookPro
                memory:
                    total: "8589934592"
                os: macOS-10.16-x86_64-i386-64bit
                program: /Users/jeremyong/Desktop/research_agent/classification/classification_models/vit.py
                python: CPython 3.12.11
                root: .
                startedAt: "2025-12-31T14:15:53.786160Z"
                writerId: 3rf1t73a69ophjp0sbi5t9pyg0izjjxk
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 63
                - 80
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 63
                - 80
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-x86_64
config:
    value: ModelConfig(model_name='tinynet_e.in1k', pretrained=False, num_classes=10, learning_rate=0.001, weight_decay=0.01)
